<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 50%;
    }
</style>
<div id="welcome">
    <h1>Seja bem vindo ao <span id="zf-name">Cadastro de Cliente!</span></h1>
    <hr />
    
    <div id="more-information">
        <br /><br />
        <h2><a href="/cliente">Ir para Listagem de Clientes</a></h2>
    </div>
</div>