<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        height: 50%;
        margin-top: 50px;
    }

    #more-information span{
        color: blue;
        font-size: 18px;
    }

</style>
<div id="welcome">
    <h2>Listagem de Clientes</h2>
    <hr/>
    <div id="more-information">
        
        <span><?php echo ($this->flashmsgs)? $this->flashmsgs[0]:'';?></span>

        <ul>
            <?php
                foreach($this->clientes as $cliente) {
                    if(empty($cliente))
                        continue;
            ?>
                <li><?php echo $cliente->getNome() . " | " . $cliente->getEmail() ?> 
                    <a href="/cliente/view/?id=<?php echo $cliente->getId();?>">Visualizar</a> 
                    <a href="/cliente/edit/?id=<?php echo $cliente->getId();?>">Editar</a> 
                    <a href="/cliente/delete/?id=<?php echo $cliente->getId();?>">Excluir</a>  
                </li>
            <?php
                }
            ?>
        </ul>
    </div>
    <?php echo $this->render('menu.phtml'); ?>
</div>