<div id="welcome">
    <h2>Listagem de Clientes
    <?php if($this->readOnly) { ?>
        <span> * Modo de Leitura </span>
    <?php } ?>
    </h2>
    <hr/>
    <div id="more-information">
        
        <span><?php echo ($this->flashmsgs)? $this->flashmsgs[0]:'';?></span>

        <ul>
            <?php
                foreach($this->clientes as $cliente) {
                    if(empty($cliente))
                        continue;
            ?>
                <li><?php echo $cliente->getNome() . " | " . $cliente->getEmail() ?> 
                    <a href="/cliente/view/?id=<?php echo $cliente->getId();?>">Visualizar</a> 
                    <?php if(!$this->readOnly) { ?>
                        <a href="/cliente/edit/?id=<?php echo $cliente->getId();?>">Editar</a> 
                        <a href="/cliente/delete/?id=<?php echo $cliente->getId();?>">Excluir</a>
                    <?php } ?>
                </li>
            <?php
                }
            ?>
        </ul>
    </div>
    <?php echo $this->render('menu.phtml'); ?>
</div>