<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        min-height: 50%;
    }

    ul{
        list-style-type: none;
    }
</style>
<div id="welcome">
    <h1>Cadastro de novo Usuário</h1>
    <hr/>
    <br />
    <div id="more-information">
        <?php echo $this->form; ?>

    </div>
    <?php echo $this->render('menu.phtml'); ?>
</div>