<div id="welcome">
    <h1>Visualização de dados do cliente</h1>
    <hr/>
    <br />
    <div id="more-information">

        <?php /*poderia ter usada a short tag <?=?>, porém não é considerada mais uma boa prática de programação*/ ?>
        <p><strong>Nome:</strong> <?php echo $this->cliente->getNome();?></p>
        <p><strong>Email:</strong> <?php echo $this->cliente->getEmail();?></p>
        <p><strong>Telefone:</strong> <?php echo $this->cliente->getTelefone();?></p>
        <p><strong>CPF:</strong> <?php echo $this->cliente->getCpf();?></p>
        <br>
    </div>
    <?php echo $this->render('menu.phtml'); ?>
</div>